version: '3'

services:
  node:
    container_name: react-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    command: 'npm start'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

  